### PR TITLE
[WIP] Privacy Policy

### PR DESCRIPTION
**Pull request by kelvinabrokwa**

### CODE REVIEW

**Comment by RyanBeatty** [comment]
@kelvinabrokwa Why is there so many css/javascript/img additions? It looks like we don't use alot of the stuff thats being added (like the images). It also looks like you've put a duplicate version of bootstrap in there. Could we remove alot of that?

**Comment by kelvinabrokwa** [comment]
@RyanBeatty as for the duplicate Bootstrap we can throw that out once we figure out the path problem. 

For the other assets it might take some doing to get rid of the ones we don't use. This html was generated by some site that @ugiacoman used so it all came wrapped up together.

One option could be a script that crawls all the html and indexes all `href` and `src` attributes in html tags and then programmatically deletes assets that it doesn't find. That might take a bit of doing depending on the language I choose for that (probs bash though).

**Comment by RyanBeatty** [comment]
@kelvinabrokwa Ah I see I see. Yeah well remove the bootstrap, and we'll have to figure out what to do with the other asset stuff when we are free. What was the issue with catch-all urls you were having?

**Comment by kelvinabrokwa** [comment]
@RyanBeatty basically when you go to a path beneath `/privacy-policy` (the think the privacy policy stuff is all iframes with these other html files) like `/privacy-policy/location-services` the page requests assets at urls likes `/privacy-policy/static/privacy-policy/css/main.css ` instead of just `/static/privacy-policy/css/main.css `

**Pull request merged**
