### PR TITLE
[NOT READY] Landing page

### PR DESCRIPTION
**Pull request by kelvinabrokwa**
On mobile

On computer
screenshot 2015-08-27 14 43 08

### CODE REVIEW

**Comment by newOnahtaN** [comment]
As far a styling goes, we're using a new color palette now. I shared the google drive with the new colors and designs inside of it made by Corynne, and another guide is the william and mary visual identity guide which we are following: 
http://styleguide.wm.edu/

**Comment by kelvinabrokwa** [comment]
I really don't want to deal with a rebase so I'm going to restart this PR on a new branch.

**Comment by newOnahtaN** [comment]
Apologies!! Just for clarification, the landing page is a separate page from the login page, there should just be a link to the login page that explicitly says its for drivers only.

**Comment by kelvinabrokwa** [comment]
@newOnahtaN no worries! My fault for being slow.

And yeah, I'm making the landing page the root path and in the upper right there is a link that says `Driver Login` that routes to `/login.html`

**Comment by newOnahtaN** [comment]
No fault at all! You're anything but slow hahahahahaha.

**Comment by kelvinabrokwa** [comment]
done in https://github.com/RyanBeatty/Steer-Clear-Backend/pull/32

**Pull request closed without merging**
